# Site settings
title: 布拉格
email: leichaomin@126.com
description: > # this means to ignore newlines until "baseurl:"
  Study and entertainment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
